name: Run Daily Email Script

# Schedule the script to run daily at 7 AM IST
on:
  schedule:
    - cron: "*30 1 * * *"  # 1:30 AM UTC (equivalent to 7 AM IST)

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository containing the script
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies (e.g., smtplib, pandas)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # Step 4: Run the email script
      - name: Run daily_email.py
        env:
          EMAIL: ${{ secrets.EMAIL }}  # GitHub Secrets for email address
          PASSWORD: ${{ secrets.PASSWORD }}  # GitHub Secrets for app password
        run: |
          python daily_email.py
